server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${dbi.datasource.driver-class-name}
      url: jdbc:mysql://${dbi.datasource.host}:${dbi.datasource.port}/${dbi.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${dbi.datasource.username}
      password: ${dbi.datasource.password}

mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cmcc.dbi.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

# 日志输出相关配置
logging:
  level:
    cmcc:
      dbi:
        mapper: debug
        service: info
        controller: info

dbi:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: cmitdbi
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: token